### ISSUE TITLE
Update README to include the process for going from 0 to interacting in the browser

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir-in-an-afternoon#1]
### Aim

It would be helpful to write out the process that you go through in the workshop video, so when people come and review this resource later on they can jump right to the section that they are having trouble with. 

Linking to relevant sections of the workshop source code would be helpful as well. 

### Expected Behavior

na

### Bug

na

### To Reproduce

1.
2.
3.
4.

### Would you like to submit a PR for this Issue?

No

**Comment by signorecello** [comment]
@critesjosh i think the "guide" in the docs covers this, should we close it?
